In [ ]:
#1

""" What is a database? Differentiate between SQL and NoSQL databases. """

#Answers

""" 
Database is a collection of related data and data is a collection of facts and figures that can be processed to produce information.

Mostly data represents recordable facts. Data aids in producing information, which is based on facts.

A database management system stores data in such a way that it becomes easier to retrieve, manipulate, and produce information. 

"""

#Diffrence between SQL and NoSQL

""" 
#Type :

SQL databases are primarily called as Relational Databases (RDBMS); 

whereas NoSQL database are primarily called as non-relational or distributed database. 

#Language :

SQL databases defines and manipulates data based structured query language (SQL). 
Seeing from a side this language is extremely powerful. SQL is one of the most versatile and widely-used options available which makes it a safe choice especially for great complex queries. 
But from other side it can be restrictive. SQL requires you to use predefined schemas to determine the structure of your data before you work with it. 
Also all of your data must follow the same structure.

A NoSQL database has dynamic schema for unstructured data. 
Data is stored in many ways which means it can be document-oriented, column-oriented, graph-based or organized as a KeyValue store. 
This flexibility means that documents can be created without having defined structure first. Also each document can have its own unique structure. 
The syntax varies from database to database, and you can add fields as you go. 

#Scalability : 

In almost all situations SQL databases are vertically scalable. 
This means that you can increase the load on a single server by increasing things like RAM, CPU or SSD. 

But on the other hand NoSQL databases are horizontally scalable. 
This means that you handle more traffic by sharding, or adding more servers in your NoSQL database. 
Thus NoSQL can ultimately become larger and more powerful, making these databases the preferred choice for large or ever-changing data sets.

#Structure : 

SQL databases are table-based on the other hand NoSQL databases are either key-value pairs, document-based, graph databases or wide-column stores. 
This makes relational SQL databases a better option for applications that require multi-row transactions such as an accounting system or for legacy systems that were built for a relational structure. 

#Property followed :
 
SQL databases follow ACID properties (Atomicity, Consistency, Isolation and Durability) 
whereas the NoSQL database follows the Brewers CAP theorem (Consistency, Availability and Partition tolerance). 

#Support :
 
Great support is available for all SQL database from their vendors. 
Also a lot of independent consultations are there who can help you with SQL database for a very large scale deployments 
but for some NoSQL database you still have to rely on community support and only limited outside experts are available 
for setting up and deploying your large scale NoSQL deployments.

"""

In [ ]:
#2

""" Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example. """

#Answer

""" 
DDL is an abbreviation of Data Definition Language.

The DDL Commands in Structured Query Language are used to create and modify the schema of the database and its objects. 

The syntax of DDL commands is predefined for describing the data. The commands of Data Definition Language deal with how the data should exist in the database.
"""

""" 
Following are the five DDL commands in SQL:

CREATE Command
DROP Command
ALTER Command
TRUNCATE Command
RENAME Command

"""

#Examples

#Create

#CREATE is a DDL command used to create databases, tables, triggers and other database objects.

""" 
CREATE TABLE Table_name   
(  
Roll_No. Int ,    
First_Name Varchar (20) ,    
Last_Name Varchar (20) ,    
Age Int ,  
Marks Int ,   
) ;     
"""

#DROP

#DROP is a DDL command used to delete/remove the database objects from the SQL database. 
# We can easily remove the entire table, view, or index from the database using this DDL command.

""" 
DROP TABLE Table_Name;  
"""

#Alter

#ALTER is a DDL command which changes or modifies the existing structure of the database, and it also changes the schema of database objects.
#We can also add and drop constraints of the table using the ALTER command.

""" 
ALTER TABLE Table_Name ADD Father's_Name Varchar(60);  
"""

#Truncate

#TRUNCATE is another DDL command which deletes or removes all the records from the table.
#This command also removes the space allocated for storing the table records.

""" 
TRUNCATE TABLE Table_Name;  
"""

In [ ]:
#3

""" Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example. """

#Answers

""" 
DML is an abbreviation of Data Manipulation Language.

The DML commands in Structured Query Language change the data present in the SQL database. 

We can easily access, store, modify, update and delete the existing records from the database using DML commands.

Following are the four main DML commands in SQL:

SELECT Command
INSERT Command
UPDATE Command
DELETE Command

"""

#Examples


#Insert

""" 
INSERT is another most important data manipulation command in Structured Query Language, which allows users to insert data in database tables.


# INSERT INTO Student (Stu_id, Stu_Name, Stu_Marks, Stu_Age) VALUES (104, Anmol, 89, 19);  

"""
#Update

""" 
UPDATE is another most important data manipulation command in Structured Query Language, which allows users to update or modify the existing data in database tables.


# UPDATE Student SET Stu_Marks = 80, Stu_Age = 21 WHERE Stu_Id = 103 AND Stu_Id = 202;  

"""
#DELETE

""" 
DELETE is a DML command which allows SQL users to remove single or multiple existing records from the database tables.
This command of Data Manipulation Language does not delete the stored data permanently from the database. 
We use the WHERE clause with the DELETE command to select specific rows from the table.

# DELETE FROM Student WHERE Stu_Marks > 70 ;  

"""

In [ ]:
#4

""" Q4. What is DQL? Explain SELECT with an example. """

#Answers

""" DQL statements are used for performing queries on the data within schema objects. 
The purpose of the DQL Command is to get some schema relation based on the query passed to it. 

List of DQL: 

SELECT: It is used to retrieve data from the database.
"""

#Select 

""" 
SELECT is the most important data manipulation command in Structured Query Language. 
The SELECT command shows the records of the specified table. 
It also shows the particular record of a particular column by using the WHERE clause.


# SELECT * FROM Student;  

"""

In [ ]:
#5

""" Q5. Explain Primary Key and Foreign Key. """

#Answer

"""
#Primary Key: 

A primary key is used to ensure that data in the specific column is unique. 
A column cannot have NULL values. It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. 

#Foreign Key: 

A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. 
It is a column (or columns) that references a column (most often the primary key) of another table. 

"""

In [ ]:
#6

""" Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method. """

#Answer

#Cursor()

""" 
It is an object that is used to make the connection for executing SQL queries. 
It acts as middleware between SQLite database connection and SQL query. 
It is created after giving connection to SQLite database.
"""

#execute()

""" It is an object method over the cursor and This method executes the given database query. """

import mysql.connector

mydb = mysql.connector.connect(
  host="localhost",
  user="yourusername",
  password="yourpassword"
)

mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE DBname ")

In [ ]:
#7

""" Q7. Give the order of execution of SQL clauses in an SQL query. """

#  Answer
"""
SQL queries adhere to a specific order when evaluating clauses, similar to how mathematical operations adhere to PEMDAS or BIDMAS.

From the eyes of the user, queries begin from the first clause and end at the last clause. However, queries arent actually read from top to bottom when carried out.

The order in which the clauses in queries are executed is as follows:

1. FROM/JOIN: The FROM and/or JOIN clauses are executed first to determine the data of interest.

2. WHERE: The WHERE clause is executed to filter out records that do not meet the constraints.

3. GROUP BY: The GROUP BY clause is executed to group the data based on the values in one or more columns.

4. HAVING: The HAVING clause is executed to remove the created grouped records that dont meet the constraints.

5. SELECT: The SELECT clause is executed to derive all desired columns and expressions.

6. ORDER BY: The ORDER BY clause is executed to sort the derived values in ascending or descending order.

7. LIMIT/OFFSET: Finally, the LIMIT and/or OFFSET clauses are executed to keep or skip a specified number of rows.

"""